# Generated by Django 2.0.2 on 2018-02-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_remove_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
